### ISSUE TITLE
part corrections for hub

### ISSUE THREAD

**Issue by eschultz** [valordk/chordata#1]
Thanks for creating mini versions of the Chordata hub and k-ceptors!

A couple of issues I discovered from the Hub's BOM:

1. #5 HEADER-SBC - Mouser part no. should be 649-1012938390601ALF  with a price of $0.76/each

2. Remove #8 and #9 - they are not used on the Hub

**Comment by zaanen** [comment]
Eric is this already fixed or is it still wrong in the BOM ?

**Comment by valordk** [comment]
This is now fixed in the latest BOM, as I've updated on the build log: https://forum.chordata.cc/d/71-mini-k-ceptor-design/81
