### ISSUE TITLE
Pick&place/centroid file?

### ISSUE THREAD

**Issue by pryda-snare** [valordk/chordata#2]
Could you include a Pick&place/centroid file for ordering assembly? I don't think i can create it from the Gerber Files Alone.

**Comment by valordk** [comment]
Hi @pryda-snare ,
The schematics and the PCB sources can also be found on my Easyeda repository

[https://easyeda.com/Muza/vals-chordata](Mini K-Ceptor)
[https://easyeda.com/Muza/vals-chordata-mini-hub-v1_copy](Mini Hub)

I built them by hand so no Pick&Place files were neccessary. You are welcome to clone the Easyeda repos and recheck the parts to ensure that the placement and oritentation fits your assembly fab. and the components they have in stock.

**Comment by pryda-snare** [comment]
Hi Valor, 

thanks for your response.
i see only the minihub v. 1.0 on easyeda do you have version 1.3 as on your github?

the k-ceptor is 1.3, which is the newest. 
And have you had success with your design, are they working well?

Dec 1, 2020, 08:56 by notifications@github.com:

**Comment by valordk** [comment]
The most recent Mini Hub version is v1.0 since it did not require any modifications.
I've built mine and it works. Please refer to Chrodata discussion board where other users are building it.

**Comment by pryda-snare** [comment]
Dear valor,

In the kceptor
It seems there are 3 RLB in BOM but only one in the Gerber.

Would you know which is the correct?



5. dec. 2020 17.10 af andersen@tuta.io:

**Comment by valordk** [comment]
> 
> Dear valor, In the kceptor It seems there are 3 RLB in BOM but only one in the Gerber. Would you know which is the correct? 5. dec. 2020 17.10 af andersen@tuta.io:


These are used to set a unique i2c address within a chain. You will have to select one during the assembly of a particular mini K-Ceptor.
These particular values are selected from the datasheet for the LTC4316 i2c Address Translator
![image](https://user-images.githubusercontent.com/15346053/103518307-d368d300-4e73-11eb-8bf6-cc194aecb9b6.png)

**Comment by pryda-snare** [comment]
Ah so the first in a chain will have R0, then 102k, then 182k.

**Comment by valordk** [comment]
Yes ;)

**Comment by valordk** [comment]
It's also shown on my build-log at https://forum.chordata.cc/d/71-mini-k-ceptor-design/7

![image](https://user-images.githubusercontent.com/15346053/103536263-7af4fe00-4e92-11eb-8ddc-aa7f21b2784c.png)
